# Generated by Django 5.1.2 on 2024-12-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ongs', '0002_ong_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Agente', max_length=60, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='CPF do Agente', max_length=18, unique=True, verbose_name='CPF')),
                ('fone', models.CharField(help_text='Telefone do Agente', max_length=15, verbose_name='Fone')),
                ('ong', models.ForeignKey(help_text='ONG de Atuação', on_delete=django.db.models.deletion.PROTECT, to='ongs.ong', verbose_name='ONG')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
            },
        ),
    ]
