# Generated by Django 5.1.2 on 2024-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agente',
            name='fone',
        ),
        migrations.AlterField(
            model_name='agente',
            name='email',
            field=models.CharField(help_text='Email do Agente', max_length=30, verbose_name='Email'),
        ),
    ]
