# Generated by Django 5.1.2 on 2024-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='cpf',
            field=models.CharField(help_text='CPF do Agente', max_length=18, unique=True, verbose_name='CPF'),
        ),
    ]
