# Generated by Django 5.1.2 on 2024-11-04 00:38

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Logotipo da ONG', null=True, upload_to='logos', variations={}, verbose_name='Foto'),
        ),
    ]
