# Generated by Django 5.1.2 on 2024-11-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60, verbose_name='Tipo')),
                ('quantidade', models.CharField(max_length=10, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Financiamento',
                'verbose_name_plural': 'Financiamentos',
            },
        ),
    ]
