# Generated by Django 5.1.2 on 2024-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financimento',
            name='nome',
            field=models.CharField(default=11, help_text='ID do financiamento', max_length=6, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financimento',
            name='quantidade',
            field=models.CharField(help_text='Quantidade a ser Doada', max_length=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='financimento',
            name='tipo',
            field=models.CharField(help_text='Tipo de financiamento', max_length=60, verbose_name='Tipo'),
        ),
    ]
