# Generated by Django 5.1.2 on 2025-05-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0002_financimento_nome_alter_financimento_quantidade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Financimento',
            new_name='Financiamento',
        ),
    ]
