# Generated by Django 5.1.2 on 2024-11-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=60, verbose_name='Tipo')),
                ('data', models.CharField(max_length=20, verbose_name='Data')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('populacao', models.CharField(max_length=10, verbose_name='População')),
            ],
            options={
                'verbose_name': 'Desastre',
                'verbose_name_plural': 'Desastres',
            },
        ),
    ]
