# Generated by Django 5.1.2 on 2024-11-07 18:06

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desastres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desastre',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='desastres', variations={}, verbose_name='Foto'),
        ),
    ]
