# Generated by Django 5.1.2 on 2024-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desastres', '0002_desastre_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desastre',
            name='populacao',
            field=models.CharField(max_length=10, verbose_name='Vítimas'),
        ),
    ]
