# Generated by Django 5.1.2 on 2024-12-18 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desastres', '0003_alter_desastre_populacao'),
        ('ongs', '0002_ong_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(help_text='Nome da Operação', max_length=100, verbose_name='Operação')),
                ('desastre', models.ForeignKey(help_text='Nome do desastre', on_delete=django.db.models.deletion.CASCADE, to='desastres.desastre', verbose_name='Desastre')),
                ('ong', models.ForeignKey(help_text='Nome do ONG', on_delete=django.db.models.deletion.CASCADE, to='ongs.ong', verbose_name='Ong')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
            },
        ),
    ]
