# Generated by Django 5.1.2 on 2024-11-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('local', models.CharField(max_length=100)),
                ('capacidade', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Abrigo',
                'verbose_name_plural': 'Abrigos',
            },
        ),
    ]
