# Generated by Django 5.1.2 on 2024-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrigo',
            name='capacidade',
            field=models.CharField(help_text='Capacidade do Abrigo', max_length=10, verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='abrigo',
            name='local',
            field=models.CharField(help_text='Localização do Abrigo', max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='abrigo',
            name='nome',
            field=models.CharField(help_text='Nome do Abrigo', max_length=60, verbose_name='Nome'),
        ),
    ]
