# Generated by Django 5.1.2 on 2024-12-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abrigos', '0002_alter_abrigo_capacidade_alter_abrigo_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(help_text='Função do agente', max_length=30, verbose_name='Função')),
                ('duracao', models.CharField(help_text='Duração da missão', max_length=20, verbose_name='Duração')),
                ('abrigo', models.ForeignKey(help_text='Nome do abrigo', on_delete=django.db.models.deletion.CASCADE, related_name='abrigo', to='abrigos.abrigo', verbose_name='Abrigo')),
            ],
            options={
                'verbose_name': 'Missão do agente',
                'verbose_name_plural': 'Missões do agente',
            },
        ),
    ]
