# Generated by Django 5.1.2 on 2024-12-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentemissao', '0001_initial'),
        ('agentes', '0001_initial'),
        ('desastres', '0003_alter_desastre_populacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentemissao',
            name='agente',
            field=models.ForeignKey(help_text='Nome do agente', on_delete=django.db.models.deletion.CASCADE, related_name='agente', to='agentes.agente', verbose_name='Agente'),
        ),
        migrations.AddField(
            model_name='agentemissao',
            name='desastre',
            field=models.ForeignKey(help_text='Nome do desastre', on_delete=django.db.models.deletion.CASCADE, related_name='desastre', to='desastres.desastre', verbose_name='Desastre'),
        ),
    ]
